language: csharp
solution: Facebook.sln
os: osx
env:
  global:
  - ANDROID_HOME='/usr/local/share/android-sdk'
  - JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
mono:
- 5.0.1
install:
- nuget restore Facebook.sln
- sh scripts/travis/install.sh
- sh scripts/setup.sh

stages:
  - name: test
    if: '! tag =~ /^sdk-version-([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/'
  - name: release
    if: tag =~ /^sdk-version-([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

jobs:
  include:
    - stage: test
      name: Unity Tests
      script: sh scripts/run_tests.sh
    - stage: release
      name: GitHub Release
      script: sh scripts/package_sdk.sh
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_ACCESS_TOKEN
        file: out/*
        file_glob: true
        name: Facebook SDK $TRAVIS_TAG
        body: Consult Changelog $TRAVIS_TAG
        on:
          all_branches: true
          tags: true
